[package]
name = "rust-berlin-leptos"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
leptos = { version = "0.7.7", features = ["csr"] }
thaw = { version = "0.4.3", features = ["csr"] }
